# Generated by Django 5.0 on 2024-02-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='AboutIMG')),
                ('quantity', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='AboutMeIMG')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='BannerIMG')),
                ('title', models.CharField(max_length=255)),
                ('mid_title', models.CharField(max_length=255)),
                ('typ_education', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='FacultyIMG')),
                ('registered', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=60)),
                ('logo', models.ImageField(upload_to='BannerImg')),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('working_time', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('fb', models.URLField()),
                ('tg', models.URLField()),
                ('insta', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registered', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnivGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='UnivGalleryIMG')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='StudentIMG')),
                ('passport', models.FileField(upload_to='StudentPassport')),
                ('certificate', models.FileField(upload_to='StudentCertificate')),
                ('ielts', models.FloatField(default=0)),
                ('gpa', models.FloatField(default=0)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='StudentBannerIMG')),
                ('contract', models.FileField(blank=True, null=True, upload_to='StudentContractFile')),
                ('date', models.DateField(auto_now=True)),
                ('gender', models.IntegerField(choices=[(1, 'Man'), (2, 'Woman')], default=1)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='UniversityIMG')),
                ('banner', models.ImageField(upload_to='UniversityBanner')),
                ('address', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('rating', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=7)),
                ('process', models.CharField(max_length=255)),
                ('control', models.CharField(max_length=255)),
                ('motto', models.CharField(max_length=255)),
                ('teachers', models.IntegerField()),
                ('registered', models.IntegerField(default=0)),
                ('degree', models.ManyToManyField(to='main.degree')),
                ('faculty', models.ManyToManyField(to='main.faculty')),
                ('language', models.ManyToManyField(to='main.language')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region')),
                ('sessions', models.ManyToManyField(to='main.sessions')),
                ('gallery', models.ManyToManyField(to='main.univgallery')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.university'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.FileField(upload_to='RegisPast')),
                ('certificate', models.FileField(upload_to='RegisCertificate')),
                ('lifetime', models.DateField()),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'received'), (2, 'cancelled'), (3, 'in_progres')], default=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.university')),
            ],
        ),
    ]
